name: My First ci/cd action
on: [push]
jobs:
    welcome:
        runs-on: ubuntu-latest
        steps:
            - uses: Hollayemi/implite-code
            - run: tree
    
    what-are-you-here-for:
        runs-on: ubuntu-latest
        steps:
            - run: echo "why here"
        