name: My First ci/cd action
on: [push]
jobs:
    welcome:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Your are welcome to step 1 (again)"
            - run: echo "Your are welcome to step 1 (again)"
    
    what are you here for:
        runs-on: ubuntu-latest
        steps:
            - run: echo "why here"
        